name: game_store
description: A sample web application
dependencies:
  polymer: '>=0.15.5+3 <0.16.0'
  paper_elements: '>=0.6.1 <0.7.0'
  browser: '>=0.10.0+2 <0.11.0'
  path: '>=1.3.3 <1.4.0'
  route: '>=0.4.6 <0.5.0'
dev_dependencies:
  unittest: '>=0.11.5+4 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      web/css/app.css: false 
